version: '3.1'

services:
  db:
    image: 'mysql:8.4'
    container_name: demo_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    volumes:
      - /home/ajohnson/Documents/java/demo/data:/var/lib/mysql
